<?php

namespace Wpai\JetEngine;

/**
 * The format generated by the Addon API is the following:
 * array [
 *  "Swimming Pool",
 *  "Garage",
 *  "Garden or Yard"
 * ]
 *
 * If "Save as array" is disabled, the format expected by JetEngine is:
 * array [
 *   "Swimming Pool" => "true"
 *   "Garage" => "true"
 *   "Garden or Yard" => "true"
 * ]
 */
class AsCheckbox {
    public function __invoke($field, $value, $post_id, $post_type) {

        if ('_jet_engine_relations' === $field['group'] || $field['args']['is_array'] ?? false) {
            return $value;
        }

        $choices = [];

       if ( isset( $field['choices'] ) && is_array( $field['choices'] ) ) {
            foreach ($field['choices'] as $key => $choice) {
                $choices[ $choice['value'] ] = "false";
            }
       }

       foreach ( $value as $choice ) {
            $choices[ $choice ] = "true";
       }

        return $choices;
    }
}

/**
 * The format generated by the Addon API is the following:
 * array [
 *  ["name" => "Swimming Pool"],
 *  ["name" => "Garage"],
 *  ["name" => "Garden or Yard"]
 * ]
 *
 * But the format expected by JetEngine is:
 * array [
 *   "item-0" => ["name" => "Swimming Pool"],
 *   "item-1" => ["name" => "Garage"],
 *   "item-2" => ["name" => "Garden or Yard"]
 * ]
 */
class AsRepeater {
    public function __invoke($field, $value, $post_id, $post_type) {
        $keys = array_map(fn ($i) => "item-$i", array_keys($value));
        return array_combine($keys, $value);
    }
}

class AsMedia {
    public function __invoke($field, $value, $post_id, $post_type) {
        $format = $field['args']['value_format'] ?? 'id';

        if ($format === 'both') {
            return [
                'id' => $value,
                'url' => wp_get_attachment_url($value),
            ];
        }

        if ($format === 'url') {
            return wp_get_attachment_url($value);
        }

        return $value;
    }
}

class AsGallery {
    public function __invoke($field, $value, $post_id, $post_type) {
	    $format = $field['args']['value_format'] ?? 'id';

        $transform = new AsMedia;

        $value = array_map(
            fn ($id) => $transform($field, $id, $post_id, $post_type),
            $value
        );

		// Ids are expected to be comma delimited instead of in an array.
	    // Either works in JetEngine itself, but the wrong format will break integrations.
	    if('id' === $format){
			$value = implode(',', $value);
	    }

		return $value;
    }
}